//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLlt03_atencion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLlt03_atencion()
        {
            this.CLIt01_anamnesis = new HashSet<CLIt01_anamnesis>();
            this.CLlt12_examenFisico = new HashSet<CLlt12_examenFisico>();
            this.CLlt13_funcionVital = new HashSet<CLlt13_funcionVital>();
            this.CLlt10_estudioCompl = new HashSet<CLlt10_estudioCompl>();
            this.CLlt08_diagnostico = new HashSet<CLlt08_diagnostico>();
            this.CLlt11_evolucion = new HashSet<CLlt11_evolucion>();
            oListAtencion = new List<CLlt03_atencion>();
            oListDiagnostico = new List<CLlt08_diagnostico>();
            oListEstudioCompl = new List<CLlt10_estudioCompl>();
            oListEvolucion = new List<CLlt11_evolucion>();
            oListExamenFisico = new List<CLlt12_examenFisico>();
            oFuncionVital = new CLlt13_funcionVital();
            oListTratamiento = new List<CLlt16_tratamiento>();
            oAnamnesis = new CLIt01_anamnesis();
            oPaciente = new RHUt07_paciente();
            oDiagnostico = new CLlt08_diagnostico();
            oTratamientoDtl = new CLlt17_tratamientoDtl();
            oEstudioCompl = new CLlt10_estudioCompl();
            oEvolucion = new CLlt11_evolucion();
            oTratamiento = new CLlt16_tratamiento();
            oTratamientoDtl = new CLlt17_tratamientoDtl();
            oExamenFisico = new CLlt12_examenFisico();
            
        }
    
        public long idAtencion { get; set; }
        [Required(ErrorMessage = "Debe Insertar un Codigo")]
        [StringLength(10)]
        public string codAtencion { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public string idUsuario { get; set; }
        public Nullable<long> idCita { get; set; }
        public List<CLlt03_atencion> oListAtencion { get; set; }
        public List<CLlt11_evolucion> oListEvolucion { get; set; }
        public List<CLlt08_diagnostico> oListDiagnostico { get; set; }
        public List<CLlt16_tratamiento> oListTratamiento { get; set; }
        public CLIt01_anamnesis oAnamnesis { get; set; }
        public CLlt03_atencion oAtencion { get; set; }
        public CLlt11_evolucion oEvolucion { get; set; }
        public CLlt16_tratamiento oTratamiento { get; set; }
        public CLlt17_tratamientoDtl oTratamientoDtl { get; set; }
        public CLlt10_estudioCompl oEstudioCompl { get; set; }
        public List<CLlt10_estudioCompl> oListEstudioCompl { get; set; }
        public CLlt13_funcionVital oFuncionVital { get; set; }
        public List<CLlt12_examenFisico> oListExamenFisico { get; set; }

        public RHUt07_paciente oPaciente { get; set; }

        public CLlt08_diagnostico oDiagnostico { get; set; }
        public CLlt12_examenFisico oExamenFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt01_anamnesis> CLIt01_anamnesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt12_examenFisico> CLlt12_examenFisico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt13_funcionVital> CLlt13_funcionVital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt10_estudioCompl> CLlt10_estudioCompl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt08_diagnostico> CLlt08_diagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt11_evolucion> CLlt11_evolucion { get; set; }
        public virtual CLlt05_cita CLlt05_cita { get; set; }
    }
}
