//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int PermisoID { get; set; }
        public string RoleID { get; set; }
        public int MenuID { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
