//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt07_numeracion
    {
        public int idNumeracion { get; set; }
        public string serie { get; set; }
        public string num_corr_inicial { get; set; }
        public string num_corr_final { get; set; }
        public string num_corr_actual { get; set; }
        public int idTipoComprobante { get; set; }
        public int idSucursal { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public string idUsuario { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public string idUsuarioModificar { get; set; }
    }
}
